sudo: required
dist: trusty

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - ulimit -s 32768  # C++ compilers require a lot of memory

  # Update Ubuntu packages
  - sudo apt-get update -qq

  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - python -V

install:
  # Install dependencies in Ubuntu
  - sudo apt-get --assume-yes install gfortran

  # Install dependencies in conda
  - conda create -n reflex_env python=$TRAVIS_PYTHON_VERSION numpy libgfortran netcdf4 matplotlib pandas pytest coverage pip xray
  - source activate reflex_env

  # Install dependencies in PyPI
  - pip install pytest-cov coveralls

  - python setup.py build_ext --inplace

language:
  - python
  - fortran

os:
  - linux
  # - osx

python:
  - 2.7

script:
  - py.test reflexible -v --cov reflexible --cov-report term-missing
  # reflexible is far from being PEP8 compatible yet, but in the future maybe wise to use the line below...
  # - py.test reflexible --pep8 reflexible -v --cov reflexible --cov-report term-missing

after_success:
  - coveralls

notifications:
  email: false
